### ISSUE TITLE
Question: why are 'max-width' and 'width' equal on .container?

### ISSUE THREAD

**Issue by micschk** [leemunroe/responsive-html-email-template#121]
I understand the max-width, but doesn't also setting a fixed width (to an equal pixel value) make the e-mail effectively fixed-width? Or is this some kind of workaround/hack?

```css
/* Set a max-width, and make it display as block so it will automatically stretch  
to that width, but will also shrink down on a phone or something */
      .container {
        ...
        /* makes it centered */
        max-width: 580px;
        width: 580px; 
      }
```

In the [smashingmag](https://www.smashingmagazine.com/2017/01/introduction-building-sending-html-email-for-web-developers/#fluid) article you do use a percentage value;

```css
.container {
  max-width: 600px;
  width: 100%;
}
```
