### ISSUE TITLE
email template is not centered in Apple Mail app

### ISSUE THREAD

**Issue by vova42matters** [leemunroe/responsive-html-email-template#180]
<img width="1032" alt="Screenshot 2023-03-16 at 20 57 17" src="https://user-images.githubusercontent.com/75250381/225725367-d51a603f-9e8c-410d-b595-64ec6a301704.png">

MacOS Ventura 13.1

**Comment by vova42matters** [comment]
Fixed by adding these styles:
```css
@media all {
    body {
        margin: 0;
        padding: 0;
    }
}
```
