### ISSUE TITLE
.apple-link a {} block has no effect

### ISSUE THREAD

**Issue by benbro** [leemunroe/responsive-html-email-template#202]
The span with the apple-link class doesn't have a child.

[CSS](https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html#L280C7-L287C8):
```css
.apple-link a {
        color: inherit !important;
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        text-decoration: none !important;
      }
```

[HTML](https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html#L343):
```html
<span class="apple-link">Company Inc, 7-11 Commercial Ct, Belfast BT1 2NB</span>
```
