### ISSUE TITLE
Add Samsung Mail specific styles for phone and address

### ISSUE THREAD

**Issue by leemunroe** [leemunroe/responsive-html-email-template#72]
Samsung renders phone numbers and addresses as links, making them blue and underlined.

Adding this to `<style>` block will fix.

```css
#MessageViewBody a {
 color: inherit;
 text-decoration: none;
 font-size: inherit;
 font-family: inherit;
 font-weight: inherit;
 line-height: inherit;
}
```
